databases:
  - name: fin
    databaseName: fin
    user: fin_user

services:
  - type: web
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fin
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false